[build]
	publish = "_site"
	command = "npm install tailwindcss && npm run build"

[build.environment]
  NODE_VERSION = "18"
  # 临时移除NODE_ENV设置确保devDependencies安装
  ELEVENTY_CACHE_DIR = ".cache"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache",
    "node_modules",
    "node_modules/.cache"
  ]
