[build]
	publish = "_site"
	command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  ELEVENTY_CACHE_DIR = ".cache"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    ".cache",
    "node_modules/.cache"
  ]
