[build]
	publish = "_site"
	command = "npm run build"

[build.environment]
  # 启用更快的Eleventy增量构建
  ELEVENTY_RUN_MODE = "build"
  ELEVENTY_CACHE_DIR = ".cache"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/img", # Eleventy Image Disk Cache
    ".cache", # Eleventy和图片缓存
    "node_modules/.cache" # 其他构建工具缓存
  ]

# 优化构建性能
[context.production.environment]
  NODE_ENV = "production"
  ELEVENTY_CACHE = "true"
