name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Persist npm cache
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: eleventy-fetch-node-${{ hashFiles('**/package.json') }}

            - name: Persist Eleventy .cache
              uses: actions/cache@v3
              with:
                  path: ./.cache
                  key: eleventy-fetch-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      eleventy-fetch-

            - name: Debug cache info
              run: |
                  echo "Cache key: eleventy-fetch-${{ hashFiles('**/package.json') }}"
                  ls -la .cache || echo "No .cache directory"

            - name: Persist Eleventy img cache
              uses: actions/cache@v3
              with:
                  path: _site/img
                  key: eleventy-fetch-img-cache-${{ hashFiles('**/package.json') }}

            - run: npm install
            - run: npm run build

            - name: Verify cache
              run: ls -la .cache || echo "No .cache directory after build"

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_site
